Repository iCHEF/gypcrete, pull requests merged in 2019-04, with the labels that each got.

#202 Refactor 'closable()' mixin to use React's own events mechanism
  CHANGELOG.md
  packages/core/src/Popover.js
  packages/core/src/mixins/__tests__/closable.test.js
  packages/core/src/mixins/closable.js
  packages/core/src/styles/Closable.scss
Labels: enhancement

#204 Chore/remove storybook mangle
  CHANGELOG.md
  packages/storybook/.storybook/webpack.config.js
  packages/storybook/package.json
  yarn.lock
Labels: bug

#205 Refactor <TextInput> to match latest design
  CHANGELOG.md
  packages/core/package.json
  packages/core/src/Text.js
  packages/core/src/TextInput.js
  packages/core/src/__tests__/Text.test.js
  packages/core/src/__tests__/TextInput.test.js
  packages/core/src/mixins/__tests__/rowComp.test.js
  packages/core/src/mixins/rowComp.js
  packages/core/src/styles/RowComp.scss
  packages/core/src/styles/Text.scss
  packages/core/src/styles/TextInput.scss
  packages/form/src/TextInputRow.js
  packages/form/src/__tests__/TextInputRow.test.js
  packages/storybook/examples/core/TextInput/BasicUsage.js
  packages/storybook/examples/core/TextInput/CustomRendering.js
  packages/storybook/examples/core/TextInput/MultiLines.js
  packages/storybook/examples/core/TextInput/WithStatus.js
  packages/storybook/examples/core/TextInput/index.js
  packages/storybook/examples/form/TextInputRow/BasicUsage.js
Labels: breaking

#206 [Storybook] Fix yarn start not work due to adding minimizer in dev env #trivial
  packages/storybook/.storybook/webpack.config.js
Labels: bug
