Repository iCHEF/gypcrete, pull requests merged in 2019-05, with the labels that each got.

#209 Enhance <ImageEditor> for get canvas and controllable scale
  CHANGELOG.md
  packages/imageeditor/src/__tests__/index.test.js
  packages/imageeditor/src/index.js
  packages/imageeditor/src/styles/index.scss
Labels: enhancement

#211 Allow passing children to <TextInputRow> #trivial
  packages/form/src/TextInputRow.js
  packages/form/src/__tests__/TextInputRow.test.js
Labels: bug

#210 Release 3.0.0
  CHANGELOG.md
  README.md
  lerna.json
  packages/core/package.json
  packages/core/src/Avatar.js
  packages/core/src/Popover.js
  packages/core/src/Text.js
  packages/core/src/TextInput.js
  packages/core/src/__tests__/Avatar.test.js
  packages/core/src/__tests__/Text.test.js
  packages/core/src/__tests__/TextInput.test.js
  packages/core/src/index.js
  packages/core/src/mixins/__tests__/closable.test.js
  packages/core/src/mixins/__tests__/rowComp.test.js
  packages/core/src/mixins/closable.js
  packages/core/src/mixins/rowComp.js
  packages/core/src/styles/Avatar.scss
  packages/core/src/styles/Closable.scss
  packages/core/src/styles/RowComp.scss
  packages/core/src/styles/Text.scss
  packages/core/src/styles/TextInput.scss
  packages/form/package.json
  packages/form/src/SelectOption.js
  packages/form/src/SelectRow.js
  packages/form/src/TextInputRow.js
  packages/form/src/__tests__/SelectRow.test.js
  packages/form/src/__tests__/TextInputRow.test.js
  packages/imageeditor/package.json
  packages/imageeditor/src/__tests__/index.test.js
  packages/imageeditor/src/index.js
  packages/imageeditor/src/styles/index.scss
  packages/storybook/.storybook/webpack.config.js
  packages/storybook/examples/core/Avatar/BasicAvatar.js
  packages/storybook/examples/core/Avatar/index.js
  packages/storybook/examples/core/Checkbox/BasicCheckbox.js
  packages/storybook/examples/core/List/NormalList.js
  packages/storybook/examples/core/TextInput/BasicUsage.js
  packages/storybook/examples/core/TextInput/CustomRendering.js
  packages/storybook/examples/core/TextInput/MultiLines.js
  packages/storybook/examples/core/TextInput/WithStatus.js
  packages/storybook/examples/core/TextInput/index.js
  packages/storybook/examples/form/SelectRow/WithAvatar.js
  packages/storybook/examples/form/SelectRow/index.js
  packages/storybook/examples/form/TextInputRow/BasicUsage.js
  packages/storybook/package.json
  yarn.lock
Labels: breaking, release

#212 Backport/3.0.0
  CHANGELOG.md
  README.md
  lerna.json
  packages/core/package.json
  packages/form/package.json
  packages/form/src/TextInputRow.js
  packages/form/src/__tests__/TextInputRow.test.js
  packages/imageeditor/package.json
  packages/storybook/package.json
Labels: backport

#214 Upgrade to Babel 7.4 and CoreJS 3
  CHANGELOG.md
  babel.config.js
  package.json
  packages/core/package.json
  packages/form/package.json
  packages/imageeditor/package.json
  yarn.lock
Labels: breaking

#213 Refactor <SelectList> & <SelectRow>
  CHANGELOG.md
  packages/core/package.json
  packages/form/package.json
  packages/form/src/SelectList.js
  packages/form/src/SelectRow.js
  packages/form/src/__tests__/SelectList.test.js
  packages/form/src/__tests__/SelectRow.test.js
  packages/form/src/utils/parseSelectOptions.js
  packages/imageeditor/package.json
  packages/storybook/examples/form/SelectList/MultipleControlled.js
  packages/storybook/examples/form/SelectList/MultipleMinCheck.js
  packages/storybook/examples/form/SelectList/MultipleReadOnlyOption.js
  packages/storybook/examples/form/SelectList/MultipleUncontrolled.js
  packages/storybook/examples/form/SelectList/MultipleWithoutCheckAll.js
  packages/storybook/examples/form/SelectList/SingleControlled.js
  packages/storybook/examples/form/SelectList/SingleUncontrolled.js
  packages/storybook/examples/form/SelectRow/BasicUsage.js
  packages/storybook/examples/form/SelectRow/Customize.js
  packages/storybook/examples/form/SelectRow/MultipleValues.js
  packages/storybook/examples/form/SelectRow/WithAvatar.js
  yarn.lock
Labels: breaking, enhancement
