Repository iCHEF/gypcrete, pull requests merged in 2020-02, with the labels that each got.

#246 Revamp core components storybook doc(pt. 1)
  .gitignore
  packages/core/src/Avatar.js
  packages/core/src/Button.js
  packages/core/src/Checkbox.js
  packages/core/src/EditableText.js
  packages/core/src/Text.js
  packages/storybook/examples/core/Avatar.stories.js
  packages/storybook/examples/core/Avatar/BasicAvatar.js
  packages/storybook/examples/core/Avatar/index.js
  packages/storybook/examples/core/Button.stories.js
  packages/storybook/examples/core/Button/BasicButton.js
  packages/storybook/examples/core/Button/ButtonWithStatus.js
  packages/storybook/examples/core/Button/CustomTagButton.js
  packages/storybook/examples/core/Button/DisabledButton.js
  packages/storybook/examples/core/Button/ExpandedButton.js
  packages/storybook/examples/core/Button/SolidButton.js
  packages/storybook/examples/core/Button/index.js
  packages/storybook/examples/core/Checkbox.stories.js
  packages/storybook/examples/core/Checkbox/BasicCheckbox.js
  packages/storybook/examples/core/Checkbox/CheckboxWithIndeterminate.js
  packages/storybook/examples/core/Checkbox/CheckboxWithStatus.js
  packages/storybook/examples/core/Checkbox/index.js
  packages/storybook/examples/core/ColumnView.stories.js
  packages/storybook/examples/core/ColumnView/index.js
  packages/storybook/examples/core/EditableText.stories.js
  packages/storybook/examples/core/EditableText/Alignments.js
  packages/storybook/examples/core/EditableText/BasicUsage.js
  packages/storybook/examples/core/EditableText/MultiLines.js
  packages/storybook/examples/core/EditableText/index.js
Labels: doc

#247 Revamp core components storybook doc(pt. 2)
  packages/core/src/Icon.js
  packages/core/src/IconButton.js
  packages/core/src/IconCheckbox.js
  packages/core/src/InfiniteScroll.js
  packages/storybook/examples/core/HeaderRow.stories.js
  packages/storybook/examples/core/HeaderRow/BasicUsage.js
  packages/storybook/examples/core/HeaderRow/OptionalArea.js
  packages/storybook/examples/core/HeaderRow/index.js
  packages/storybook/examples/core/Icon.stories.js
  packages/storybook/examples/core/Icon/BasicIcons.js
  packages/storybook/examples/core/Icon/CRMIcons.js
  packages/storybook/examples/core/Icon/IconColors.js
  packages/storybook/examples/core/Icon/InlineIcons.js
  packages/storybook/examples/core/Icon/InventoryIcons.js
  packages/storybook/examples/core/Icon/LargeIcon.js
  packages/storybook/examples/core/Icon/MenuPageIcons.js
  packages/storybook/examples/core/Icon/PaginationIcons.js
  packages/storybook/examples/core/Icon/PaymentIcons.js
  packages/storybook/examples/core/Icon/index.js
  packages/storybook/examples/core/IconButton.stories.js
  packages/storybook/examples/core/IconButton/BasicIconButton.js
  packages/storybook/examples/core/IconButton/index.js
  packages/storybook/examples/core/IconCheckbox.stories.js
  packages/storybook/examples/core/IconCheckbox/BasicIconCheckbox.js
  packages/storybook/examples/core/IconCheckbox/index.js
  packages/storybook/examples/core/InfiniteScroll.stories.js
  packages/storybook/examples/core/InfiniteScroll/BasicUsage.js
  packages/storybook/examples/core/InfiniteScroll/PageAsContainer.js
  packages/storybook/examples/core/InfiniteScroll/index.js
Labels: doc

#248 Revamp core components storybook doc(pt. 3)
  packages/core/src/Modal.js
  packages/storybook/examples/core/Modal.stories.js
  packages/storybook/examples/core/Modal/ClosableModalExample.js
  packages/storybook/examples/core/Modal/ModalHeader.js
  packages/storybook/examples/core/Modal/index.js
Labels: doc

#250 Fix anchored popover top position when document is scrollable
  packages/core/src/mixins/__tests__/closable.test.js
  packages/core/src/mixins/closable.js
Labels: bug

#254 Fix centered modal width
  packages/core/src/styles/Modal.scss
Labels: bug

#249 Revamp core components storybook doc(pt. 4)
  packages/core/src/List.js
  packages/core/src/SearchInput.js
  packages/core/src/mixins/__tests__/closable.test.js
  packages/core/src/mixins/closable.js
  packages/storybook/examples/core/List.stories.js
  packages/storybook/examples/core/List/NestedList.js
  packages/storybook/examples/core/List/NormalList.js
  packages/storybook/examples/core/List/SettingList.js
  packages/storybook/examples/core/List/index.js
  packages/storybook/examples/core/Popover.stories.js
  packages/storybook/examples/core/Popover/Anchored.js
  packages/storybook/examples/core/Popover/Basic.js
  packages/storybook/examples/core/Popover/DemoList.js
  packages/storybook/examples/core/Popover/index.js
  packages/storybook/examples/core/Popup.stories.js
  packages/storybook/examples/core/Popup/BasicPopup.js
  packages/storybook/examples/core/Popup/HorizontalButtons.js
  packages/storybook/examples/core/Popup/index.js
  packages/storybook/examples/core/SearchInput.stories.js
  packages/storybook/examples/core/SearchInput/BasicSearchInput.js
  packages/storybook/examples/core/SearchInput/index.js
  packages/storybook/examples/core/Section.stories.js
  packages/storybook/examples/core/Section/DemoContent.js
  packages/storybook/examples/core/Section/index.js
Labels: doc

#252 Revamp core components storybook doc(pt. 6)
  packages/core/src/EditableTextLabel.js
  packages/core/src/Text.js
  packages/core/src/TextInput.js
  packages/storybook/examples/core/EditableTextLabel.stories.js
  packages/storybook/examples/core/Text.stories.js
  packages/storybook/examples/core/Text/BasicText.js
  packages/storybook/examples/core/Text/Ellipsis.js
  packages/storybook/examples/core/Text/TextWithStatusIcon.js
  packages/storybook/examples/core/Text/index.js
  packages/storybook/examples/core/TextInput.stories.js
  packages/storybook/examples/core/TextInput/CustomRendering.js
  packages/storybook/examples/core/TextInput/MultiLines.js
  packages/storybook/examples/core/TextInput/index.js
  packages/storybook/examples/core/TextLabel.stories.js
  packages/storybook/examples/core/TextLabel/BasicTextLabel.js
  packages/storybook/examples/core/TextLabel/Editable.js
  packages/storybook/examples/core/TextLabel/TextLabelWithStatus.js
  packages/storybook/examples/core/TextLabel/TextLabelWithText.js
  packages/storybook/examples/core/TextLabel/index.js
  packages/storybook/examples/core/Tooltip.stories.js
  packages/storybook/examples/core/Tooltip/AnchoredTooltip.js
  packages/storybook/examples/core/Tooltip/BasicTooltip.js
  packages/storybook/examples/core/Tooltip/index.js
Labels: doc

#256 Backport/4.1.0
  CHANGELOG.md
  lerna.json
  package.json
  packages/core/package.json
  packages/form/package.json
  packages/imageeditor/package.json
  packages/storybook/package.json
Labels: backport

#257 Better supporting for nested list styles
  CHANGELOG.md
  packages/core/src/List.js
  packages/core/src/ListRow.js
  packages/core/src/__tests__/ListRow.test.js
  packages/core/src/styles/List.scss
  packages/core/src/styles/ListRow.scss
  packages/core/src/styles/_variables.scss
  packages/storybook/examples/core/List.stories.js
Labels: enhancement

#258 Fix formRow did not merge rowProps
  CHANGELOG.md
  packages/form/src/mixins/__tests__/formRow.test.js
  packages/form/src/mixins/formRow.js
Labels: bug
