Repository iCHEF/gypcrete, pull requests merged in 2020-03, with the labels that each got.

#259 Release/4.2.0
  CHANGELOG.md
  lerna.json
  package.json
  packages/core/package.json
  packages/core/src/List.js
  packages/core/src/ListRow.js
  packages/core/src/__tests__/ListRow.test.js
  packages/core/src/styles/List.scss
  packages/core/src/styles/ListRow.scss
  packages/core/src/styles/_variables.scss
  packages/form/package.json
  packages/form/src/mixins/__tests__/formRow.test.js
  packages/form/src/mixins/formRow.js
  packages/imageeditor/package.json
  packages/storybook/examples/core/List.stories.js
  packages/storybook/package.json
Labels: release

#260 Backport 4.2.0
  CHANGELOG.md
  lerna.json
  package.json
  packages/core/package.json
  packages/form/package.json
  packages/imageeditor/package.json
  packages/storybook/package.json
Labels: backport

#261 Fix deploy script to push tags
  CHANGELOG.md
  package.json
  scripts/deploy.sh
Labels: bug

#262 [Bugfix] Fix that we have to click twice to close gyp-closable after click in wrapped component
  packages/core/src/mixins/closable.js
Labels: bug

#263 Release/4.2.1
  CHANGELOG.md
  lerna.json
  package.json
  packages/core/package.json
  packages/core/src/mixins/closable.js
  packages/form/package.json
  packages/imageeditor/package.json
  packages/storybook/package.json
  scripts/deploy.sh
Labels: release

#264 Backport/4.2.1
  CHANGELOG.md
  lerna.json
  package.json
  packages/core/package.json
  packages/form/package.json
  packages/imageeditor/package.json
  packages/storybook/package.json
Labels: backport
